### ISSUE TITLE
Displayed badge is outdated

### ISSUE THREAD

**Issue by TomDmitriev** [int128/gradleupdate#10]
While https://gradleupdate.appspot.com/TomDmitriev/gradle-bundle-plugin/status.svg?branch=master shows Gradle 2.10, here https://github.com/TomDmitriev/gradle-bundle-plugin Gradle 2.9 is displayed. I don't know why it is so, but it seems that the image is cached somewhere, which doesn't happens with the other badges on the page.
![outdated-badge](https://cloud.githubusercontent.com/assets/3924886/11972234/841cd562-a95a-11e5-8192-1a13d8645655.png)

**Comment by int128** [comment]
GitHub caches the old image. I will try adding some headers to control cache.
https://github.com/github/markup/issues/224#issuecomment-48532178
